name: Lint and Format Check

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - express-server
          - employee-portal
          - hr-portal

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier Format Check
        run: npm run format:check
